name: Manual Amplify Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: '배포할 환경 선택 (dev 또는 prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Amplify Webhook
        run: |
          if [ "${{ github.event.inputs.target }}" == "dev" ]; then
            curl -X POST "${{ secrets.AMPLIFY_WEBHOOK_DEV }}"
          else
            curl -X POST "${{ secrets.AMPLIFY_WEBHOOK_PROD }}"
          fi
